name: Veracode Container/IaC/Secrets Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  veracode-iac-scan:
    runs-on: ubuntu-latest
    name: Veracode Container/IaC/Secrets scan
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Veracode Container/IaC/Secrets action step
        uses: veracode/container_iac_secrets_scanning@v1.0.1
        with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          command: "scan"
          type: "directory"
          source: "./terraform"
          format: "json"
          debug: true
          fail_build: true
